micronaut:
  application:
    name: mysqlMicronautDemo
  server:
    port: 8080
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    intercept-url-map:
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /redoc/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        httpMethod: GET
        access:
          - isAnonymous()

flyway:
  datasources:
    default:
      enabled: true
      url: jdbc:mysql://localhost:3306/micronaut?createDatabaseIfNotExist=true
      username: root
      password: root

jpa:
  default:
    packages-to-scan:
      - "com.solbeg"
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

r2dbc:
  datasources:
    default:
      url: r2dbc:mysql://localhost:3306/micronaut
      username: root
      password: root
      schema-generate: NONE
      dialect: MYSQL

jackson:
  # property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  deserialization:
    failOnUnknownProperties: false
  generator:
    writeNumbersAsStrings: false
    writeBigDecimalAsPlain: false