micronaut:
  application:
    name: mysqlMicronautDemo
  server:
    port: 8080

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      schemas: mn
      default-schema: mn

jpa:
  default:
    packages-to-scan:
      - "com.solbeg"
    properties:
      hibernate:
        show_sql: true

r2dbc:
  datasources:
    default:
      url: r2dbc:mysql://localhost:3306/micronaut
      username: root
      password: root
      schema-generate: NONE
      dialect: MYSQL
# JSON Global Settings
jackson:
  # property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  deserialization:
    failOnUnknownProperties: false
  generator:
    writeNumbersAsStrings: false
    writeBigDecimalAsPlain: false